Table dim_year {
  year_id int [pk]
  year int [not null]
}

Table dim_municipality {
  municipality_id varchar(32) [pk]
  municipality_name varchar [not null]
}

Table dim_industry {
  industry_id varchar(32) [pk]
  industry_name varchar [not null]
}

Table fact_bankruptcies {
  year int
  year_id int [not null]
  municipality_id varchar(32) [not null]
  industry_id varchar(32) [not null]
  bankruptcies_enterprises int
  bankruptcies_employees int

  indexes {
    (year_id, municipality_id, industry_id) [unique]
  }
}

Ref: fact_bankruptcies.year_id > dim_year.year_id
Ref: fact_bankruptcies.municipality_id > dim_municipality.municipality_id
Ref: fact_bankruptcies.industry_id > dim_industry.industry_id