Table dim_year {
  year_id int [pk]
  year int [not null]
}

Table dim_industry {
  industry_id varchar(32) [pk]
  industry_name varchar [not null]
}

Table fact_bankruptcies_by_industry {
  year int
  year_id int [not null]
  industry_id varchar(32) [not null]
  bankruptcies_enterprises int
  bankruptcies_employees int
  share_of_total_pct decimal(10,2)

  indexes {
    (year_id, industry_id) [unique]
  }
}

Ref: fact_bankruptcies_by_industry.year_id > dim_year.year_id
Ref: fact_bankruptcies_by_industry.industry_id > dim_industry.industry_id